pipeline:
  projectIdentifier: sample
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k3ssa
              namespace: harness-build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: harnessDockerHub
                    image: alpine
                    shell: Sh
                    command: |-
                      cat > Dockerfile <<_EOF_
                      # syntax=docker/dockerfile:1
                      FROM alpine AS base
                      # Declare the build argument in the build stage
                      ARG NAME="joe"
                      ARG DIR="src"

                      # Create a new stage based on "base"
                      FROM base AS build
                      # The NAME build argument is available here
                      # since it's declared in a parent stage
                      WORKDIR /$DIR
                      RUN echo "hello $NAME!"
                      _EOF_
                    resources:
                      limits:
                        memory: 50Mi
                        cpu: 100m
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gcpsales
                    host: us-east1-docker.pkg.dev
                    projectID: sales-209522
                    imageName: venkat/sample
                    tags:
                      - <+pipeline.sequenceId>
                    buildArgs:
                      NAME: <+repeat.item>.split(",")[0]
                      DIR: <+repeat.item>.split(",")[1]
          caching:
            enabled: false
            paths: []
        when:
          pipelineStatus: Success
        strategy:
          repeat:
            items:
              - venkat1, app1
              - venkat2, app2
              - venkat3, app3
  allowStageExecutions: true
  identifier: testdockertrigger
  name: test-docker-trigger
