pipeline:
  projectIdentifier: sample
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k3ssa
              namespace: harness-build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: harnessDockerHub
                    image: alpine
                    shell: Sh
                    command: |-
                      cat > Dockerfile <<_EOF_
                      FROM alpine
                      ENV APP_DIR=/xyz
                      WORKDIR /src
                      RUN mkdir -p venkat
                      RUN pwd
                      _EOF_

                      pwd
                      ls
                    resources:
                      limits:
                        memory: 50Mi
                        cpu: 100m
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gcpsales
                    host: us-east1-docker.pkg.dev
                    projectID: sales-209522
                    imageName: venkat/sample
                    tags:
                      - <+pipeline.sequenceId>
          caching:
            enabled: false
            paths: []
        when:
          pipelineStatus: Success
  allowStageExecutions: true
  identifier: testdockertrigger
  name: test-docker-trigger
