service:
  name: cx_product
  identifier: cx_product
  orgIdentifier: Nuuly
  projectIdentifier: CX
  serviceDefinition:
    type: Kubernetes
    spec:
      artifacts:
        primary:
          primaryArtifactRef: rentaldevgcr
          sources:
            - spec:
                connectorRef: org.rentaldev
                imagePath: rental-dev/cx/product
                tag: dev.latest
                registryHostname: gcr.io
              identifier: rentaldevgcr
              type: Gcr
      variables:
        - name: namespace
          type: String
          description: "namespace"
          required: false
          value: "harness-demo"
  gitOpsEnabled: true

